# Generated by Django 3.1.7 on 2021-03-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=60)),
                ('dateFabrication', models.DateField()),
                ('paysFabrikation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.pays')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
