# Generated by Django 3.1.7 on 2021-03-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_vaccin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=9)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.pays')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.vaccin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
