# Generated by Django 3.1.7 on 2021-03-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210319_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccin',
            old_name='paysFabrikation',
            new_name='paysFabrication',
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('vaccinateurs', models.ManyToManyField(to='covid.Vaccinateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
