# Generated by Django 3.2 on 2021-05-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210502_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinateur',
            name='maladies',
            field=models.ManyToManyField(null=True, to='covid.Maladie'),
        ),
    ]
