# Generated by Django 3.2 on 2021-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_vaccinateur_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinateur',
            name='email',
            field=models.EmailField(default='exemple@gmail.com', max_length=254),
        ),
    ]
