# Generated by Django 3.2 on 2021-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_alter_vaccinateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
