# Generated by Django 3.2 on 2021-05-10 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_alter_vaccinateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='vaccin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.vaccin'),
        ),
    ]
