# Generated by Django 3.2 on 2021-05-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_declaration_vaccin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='vaccin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.vaccin'),
        ),
    ]
